USE print_ims;

ALTER TABLE sys_role
    ADD COLUMN IF NOT EXISTS create_by BIGINT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS update_by BIGINT DEFAULT NULL;

ALTER TABLE sys_menu
    ADD COLUMN IF NOT EXISTS create_by BIGINT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS update_by BIGINT DEFAULT NULL;
